// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUlWWU4B3CRXpVM1geHz588Ij2oLceRKY',
    appId: '1:478132732252:web:9ee661a506cd08aebe0199',
    messagingSenderId: '478132732252',
    projectId: 'fir-auth-25634',
    authDomain: 'fir-auth-25634.firebaseapp.com',
    storageBucket: 'fir-auth-25634.appspot.com',
    measurementId: 'G-D87812ZZSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAusGhojQtr1BZaZ_dSOWRHQqDDsLgQQZY',
    appId: '1:478132732252:android:a0049e3231d8eb8bbe0199',
    messagingSenderId: '478132732252',
    projectId: 'fir-auth-25634',
    storageBucket: 'fir-auth-25634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhFaP5g3WzM9L-FIR3YMLbZiBYbtW1GAM',
    appId: '1:478132732252:ios:07c9ba77b3c11b47be0199',
    messagingSenderId: '478132732252',
    projectId: 'fir-auth-25634',
    storageBucket: 'fir-auth-25634.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhFaP5g3WzM9L-FIR3YMLbZiBYbtW1GAM',
    appId: '1:478132732252:ios:84843c1608eab800be0199',
    messagingSenderId: '478132732252',
    projectId: 'fir-auth-25634',
    storageBucket: 'fir-auth-25634.appspot.com',
    iosBundleId: 'com.example.firebaseAuth.RunnerTests',
  );
}
